### ISSUE TITLE
it cannot convert currency anymore

### ISSUE THREAD

**Issue by dtantono** [sheep-farm/merkato#6]
Hi
I use Ubuntu 22.04 and it cannot convert currency anymore. what do you think?

https://user-images.githubusercontent.com/29157187/236968079-adc25d38-6934-49f2-8091-dcdd41457d85.mp4

**Comment by sheep-farm** [comment]
Thanks for reporting the issue. I had already identified it. Next week, I'll be releasing a new version of the software. There are some interesting changes being introduced. First, we'll replace Yahoo Finance as a source, and I'm thinking of using the API from "https://brapi.dev/". Second, I plan to change the layout to something similar to what's shown on Google Finance.
