### ISSUE TITLE
Crash when trying to add any symbol

### ISSUE THREAD

**Issue by may7c** [sheep-farm/merkato#7]
Whatever symbol I try to add, it will make the app crash.
Then I try to fill a report but I cannot event do that.

I run the Flathub version, on Fedora 38.

[Capture vidéo du 2023-05-09 09-14-33.webm](https://user-images.githubusercontent.com/131338850/236977274-8cbffdca-0397-46f0-9131-d67a1a258ad1.webm)

![image](https://user-images.githubusercontent.com/131338850/236976485-c4614643-0f41-4591-9a2e-36aad999d77e.png)

**Comment by linuxtopia** [comment]
same with opensuse leap 15.4

**Comment by eject7455** [comment]
Same here on Fedora 38 with Flathub install. I'm thinking it has something to do with Yahoo's API as there is another project named Markets by bitstower which also uses Yahoo as a source and it stopped updated on May 4th. The owner then proceeded to make the repo read only and no longer maintained.
Having trouble finding a FOSS Linux app to monitor stock prices at this point. There were a couple Gnome extensions but they don't show up anymore either.

**Comment by sheep-farm** [comment]
Thanks for reporting the issue. I had already identified it. Next week, I'll be releasing a new version. There are some interesting changes being introduced. First, we'll replace Yahoo Finance as a source, and I'm thinking of using the API from "https://brapi.dev/". Second, I plan to change the layout to something similar to what's shown on Google Finance.

**Comment by junocomp** [comment]
@sheep-farm Hi, I am still having this issue. Any idea when it will be released?

**Comment by polesowa** [comment]
Confirmed. Im running Zorin OS (ubuntu) and installed as a Flatpak and having this issue as well.
